[build]
# Default target for cross-compilation to Windows
# target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "linker=mclib"]

# Tauri config
[env]
TAURI_MANIFEST_DIR = { value = "app/src-tauri/tauri.conf.json", force = true, relative = true }
