; AsioBridge Installer
; Generated by NSIS installer generation
; Copyright (c) 2024 AsioBridge

; Compiler settings
!include "MUI2.nsh"
!include "x64.nsh"
!include "LogicLib.nsh"

; Installer metadata
Name "AsioBridge"
OutFile "AsioBridge-Setup.exe"
InstallDir "$PROGRAMFILES64\AsioBridge"
InstallDirRegKey HKLM "Software\AsioBridge" "Install_Dir"
RequestExecutionLevel admin
CRCCheck on
XPStyle on

; Version information
!define VERSION "1.0.0"
!define VERSIONNUMBER "1,0,0,0"

VIProductVersion "${VERSIONNUMBER}"
VIAddVersionKey "ProductName" "AsioBridge"
VIAddVersionKey "FileDescription" "AsioBridge Virtual Audio Router"
VIAddVersionKey "LegalCopyright" "Copyright (c) 2024 AsioBridge"
VIAddVersionKey "FileVersion" "${VERSION}"
VIAddVersionKey "ProductVersion" "${VERSION}"

; Modern UI settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Pages
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

; Installer sections
Section "AsioBridge Application" SecApp
  SetOutPath "$INSTDIR"
  
  ; Copy application files
  File "dist\win-unpacked\*"
  
  ; Copy driver files (if built)
  ${If} ${FileExists} "driver\asiovadpro\x64\Release\asiovadpro.sys"
    CreateDirectory "$INSTDIR\driver"
    File "driver\asiovadpro\x64\Release\asiovadpro.sys"
    File "driver\asiovadpro\asiovadpro.inf"
    File "driver\asiovadpro\asiovadpro.cat"
  ${EndIf}
  
  ; Copy ASIO driver DLL (if built)
  ${If} ${FileExists} "driver\asiolink\x64\Release\asiobridge_asio.dll"
    File "driver\asiolink\x64\Release\asiobridge_asio.dll"
  ${EndIf}
  
  ; Create uninstaller
  WriteUninstaller "$INSTDIR\uninstall.exe"
  
  ; Create Start Menu shortcut
  CreateDirectory "$SMPROGRAMS\AsioBridge"
  CreateShortcut "$SMPROGRAMS\AsioBridge\AsioBridge.lnk" "$INSTDIR\asiobridge-app.exe"
  CreateShortcut "$SMPROGRAMS\AsioBridge\Uninstall.lnk" "$INSTDIR\uninstall.exe"
  
  ; Create desktop shortcut (optional)
  CreateShortcut "$DESKTOP\AsioBridge.lnk" "$INSTDIR\asiobridge-app.exe"
  
  ; Register file associations
  WriteRegStr HKCR "AsioBridge.Profile" "" "AsioBridge Profile File"
  WriteRegStr HKCR "AsioBridge.Profile\DefaultIcon" "" "$INSTDIR\asiobridge-app.exe,0"
  WriteRegStr HKCR "AsioBridge.Profile\Shell\Open\Command" "" '"$INSTDIR\asiobridge-app.exe" "%1"'
  
  ; Register in Add/Remove Programs
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "DisplayName" "AsioBridge"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "DisplayIcon" "$INSTDIR\asiobridge-app.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "QuietUninstallString" '"$INSTDIR\uninstall.exe" /S'
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "InstallLocation" "$INSTDIR"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "DisplayVersion" "${VERSION}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "Publisher" "AsioBridge"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "HelpLink" "https://asiobridge.com/support"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "URLInfoAbout" "https://asiobridge.com"
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge" "NoRepair" 1
  
  ; Set install directory registry key
  WriteRegStr HKLM "Software\AsioBridge" "Install_Dir" "$INSTDIR"
SectionEnd

Section "Install Virtual Audio Driver" SecDriver
  ; Check if driver files exist
  ${If} ${FileExists} "$INSTDIR\asiovadpro.sys"
    ; Copy driver files to system32
    CopyFiles "$INSTDIR\asiovadpro.sys" "$WINDIR\System32\Drivers\"
    CopyFiles "$INSTDIR\asiovadpro.inf" "$WINDIR\System32\DriverStore\FileRepository\"
    
    ; Install driver using pnputil
    ExecWait 'pnputil /add-driver "$WINDIR\System32\DriverStore\FileRepository\asiovadpro.inf" /install'
    
    ; Create service
    ExecWait 'sc create AsioBridgeVAD binpath= "$WINDIR\System32\Drivers\asiovadpro.sys" type= kernel start= demand'
  ${Else}
    ; Driver not built, skip installation
    MessageBox MB_ICONINFORMATION "Virtual Audio Driver not included in this build.`nPlease build the driver separately with WDK."
  ${EndIf}
SectionEnd

Section "-PostInstall"
  ; Write license file
  FileOpen $0 "$INSTDIR\LICENSE" w
  FileWrite $0 "MIT License`n`nCopyright (c) 2024 AsioBridge`n`nPermission is hereby granted..."
  FileClose $0
  
  ; Write README
  FileOpen $0 "$INSTDIR\README.txt" w
  FileWrite $0 "AsioBridge - Virtual Audio Router`nVersion: ${VERSION}`n`n"
  FileWrite $0 "Installation complete.`n`n"
  FileWrite $0 "To install the virtual audio driver:`n"
  FileWrite $0 "1. Open AsioBridge application`n"
  FileWrite $0 "2. Click 'Install Driver' in settings`n"
  FileWrite $0 "3. Restart your audio applications`n"
  FileClose $0
SectionEnd

; Uninstaller section
Section "Uninstall"
  ; Stop and delete driver service
  ExecWait 'sc stop AsioBridgeVAD'
  ExecWait 'sc delete AsioBridgeVAD'
  
  ; Remove driver files
  Delete "$WINDIR\System32\Drivers\asiovadpro.sys"
  
  ; Remove application files
  Delete "$INSTDIR\*"
  RMDir "$INSTDIR"
  
  ; Remove Start Menu shortcuts
  Delete "$SMPROGRAMS\AsioBridge\*"
  RMDir "$SMPROGRAMS\AsioBridge"
  
  ; Remove desktop shortcut
  Delete "$DESKTOP\AsioBridge.lnk"
  
  ; Remove registry entries
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\AsioBridge"
  DeleteRegKey HKCR "AsioBridge.Profile"
  DeleteRegKey HKLM "Software\AsioBridge"
SectionEnd
